### ISSUE TITLE
Write a HtmlHelper to handle boolean values in json data

### ISSUE THREAD

**Issue by rsleggett** [buildingblocks/bb-prototype-website-razor#12]
Code like the following for testing whether a value exists and is true in order to write out a data attribute is pretty messy and also pretty common: https://github.com/buildingblocks/bb-prototype-website-razor/blob/develop/Views/Components/content-cards/content-cards.cshtml#L3

We could use a helper like 

    @Html.If("equalHeights", "data-equal-heights") 

Something similar for classes I guess?

**Comment by jordanrobinson** [comment]
Hey @rsleggett is this the kind of thing you were thinking of? If so can we close?

**Comment by rsleggett** [comment]
That's exactly what I was thinking of! 👍  🥇
