### ISSUE TITLE
2 project.jsons

### ISSUE THREAD

**Issue by rsleggett** [buildingblocks/bb-prototype-website-razor#3]
There's a project.json in the data folder which I think is from the existing BB prototype project. It has a project.lock.json generated for it by VS - this might conflict with the project.json at the root which is part of the dotnetcore
project.

```
{
    "appName": "bb-prototype-website-razor",
    "title": "bb-prototype-website-razor",
    "client": "BB",
    "images": "images",
    "clientImage": "_bb/bb-mosaic.svg",
    "clientLogo": "_bb/bb-logo.svg"
}
```
`

**Comment by jordanrobinson** [comment]
Good point, I kind of have to defer to @ablackledge on what it's actually used for.

It doesn't _seem_ to be causing issues at the minute as far as I can tell but we should still clean it up.

**Comment by aFrontendDev** [comment]
It's from the old grunt project, not used in new gulp 'Jordan' branch so shouldn't be needed here if it's all working off the gulp build

**Comment by jordanrobinson** [comment]
Awesome, deleted then.

**Comment by bb-ceccles** [comment]
The project.json is used for the views to add in global variables . So it being removed it is now throwing errors. I will re add and re name.

**Comment by rsleggett** [comment]
Merged Chris' pull request - resolved.
