### ISSUE TITLE
Pre-run tasks will only work on windows at present

### ISSUE THREAD

**Issue by jordanrobinson** [buildingblocks/bb-prototype-website-razor#7]
The .cmd files in the bb-prototype-website-razor/scripts/ directory will only work on windows at the minute, so we need to make them target osx/linux also.

**Comment by rsleggett** [comment]
I've changed the project.json to run "npm install" and "gulp" as a precompile step. I've deleted the scripts directory since it didn't seem required any more. Closing this issue.
