### ISSUE TITLE
Investigate creating a NuGet package for the backend parts

### ISSUE THREAD

**Issue by rsleggett** [buildingblocks/bb-prototype-website-razor#9]
In order to avoid the front end stuff getting mixed up with the backend stuff it could be useful to create a nuget package containing the backend part of the prototype.

This would involve splitting the repo into 2.

- bb-prototype-website-razor
- bb-prototype-website-razor-framework

bb-prototype-website-razor would reference the framework as a dependency.

**Comment by bb-ceccles** [comment]
This has been implemented and merged in
